// Copyright (c) 2026 Juan Ignacio Molina Estrada
// SPDX-License-Identifier: FSL-1.1-Apache-2.0
// Generated by scripts/fetch-plugin-posters.ts — do not edit by hand.
// High-res poster art for bundled plugins, served from the terminal bundle.
// Brand marks identify the integrated venues/providers (nominative use) and
// remain trademarks of their respective owners.

export const BUNDLED_POSTERS: Record<string, string> = {
  'alpaca-market-connector': '/posters/alpaca-market-connector.png',
  'anthropic-inference': '/posters/anthropic-inference.png',
  'arbitrum-dex-connector': '/posters/arbitrum-dex-connector.png',
  'base-dex-connector': '/posters/base-dex-connector.png',
  'binance-futures-market-connector': '/posters/binance-market-connector.png',
  'binance-market-connector': '/posters/binance-market-connector.png',
  'bitfinex-market-connector': '/posters/bitfinex-market-connector.png',
  'bitget-market-connector': '/posters/bitget-market-connector.png',
  'bitvavo-market-connector': '/posters/bitvavo-market-connector.png',
  'bsc-dex-connector': '/posters/bsc-dex-connector.png',
  'bybit-futures-market-connector': '/posters/bybit-market-connector.png',
  'bybit-market-connector': '/posters/bybit-market-connector.png',
  'coinbase-market-connector': '/posters/coinbase-market-connector.png',
  'cryptocom-market-connector': '/posters/cryptocom-market-connector.png',
  'dexpaprika-data-provider': '/posters/dexpaprika-data-provider.png',
  'ethereum-dex-connector': '/posters/ethereum-dex-connector.png',
  'gate-market-connector': '/posters/gate-market-connector.png',
  'groq-inference': '/posters/groq-inference.png',
  'helius-rpc-provider': '/posters/helius-rpc-provider.png',
  'htx-market-connector': '/posters/htx-market-connector.png',
  'jupiter-dex-connector': '/posters/jupiter-dex-connector.png',
  'kalshi-market-connector': '/posters/kalshi-market-connector.png',
  'kraken-futures-market-connector': '/posters/kraken-market-connector.png',
  'kraken-market-connector': '/posters/kraken-market-connector.png',
  'kucoin-futures-market-connector': '/posters/kucoin-market-connector.png',
  'kucoin-market-connector': '/posters/kucoin-market-connector.png',
  'mexc-market-connector': '/posters/mexc-market-connector.png',
  'okx-futures-market-connector': '/posters/okx-market-connector.png',
  'okx-market-connector': '/posters/okx-market-connector.png',
  'openai-inference': '/posters/openai-inference.png',
  'openrouter-inference': '/posters/openrouter-inference.png',
  'pairlens-core': '/logo512.png',
  'pairlens-intelligence': '/logo512.png',
  'polygon-dex-connector': '/posters/polygon-dex-connector.png',
  'polymarket-market-connector': '/posters/polymarket-market-connector.png',
  'tavily-search': '/posters/tavily-search.png',
  'upbit-market-connector': '/posters/upbit-market-connector.png',
}
