// Copyright (c) 2026 Juan Ignacio Molina Estrada
// SPDX-License-Identifier: FSL-1.1-Apache-2.0
import {
  Activity,
  ArrowDownUp,
  ArrowUpDown,
  BarChart3,
  BookOpen,
  Boxes,
  Brain,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CandlestickChart,
  CircleHelp,
  Clock,
  Coins,
  Crosshair,
  Droplets,
  FileText,
  Flame,
  Gauge,
  Globe,
  Grid3X3,
  History,
  Info,
  Layers,
  LayoutGrid,
  Link2,
  ListOrdered,
  Network,
  Newspaper,
  PieChart,
  Plus,
  Receipt,
  Scale,
  ScrollText,
  Search,
  Send,
  ShieldCheck,
  ShoppingBasket,
  SlidersHorizontal,
  Sparkles,
  Star,
  Tags,
  Terminal,
  Timer,
  TrendingUp,
  Vote,
  Wallet,
  Waves,
  Waypoints,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

// A curated allowlist, not a passthrough — a plugin naming an icon we don't
// carry gets the LayoutGrid fallback rather than an arbitrary component. Every
// name a bundled pane declares in `pairlens-core` must be listed here, or that
// pane silently renders the fallback everywhere getPaneIcon is used.
const PANE_ICONS: Record<string, LucideIcon> = {
  LayoutGrid,
  Star,
  TrendingUp,
  Grid3X3,
  History,
  Newspaper,
  Gauge,
  CandlestickChart,
  ArrowUpDown,
  Brain,
  ScrollText,
  Layers,
  BookOpen,
  Receipt,
  Info,
  Search,
  Globe,
  ShieldCheck,
  Plus,
  Sparkles,
  Terminal,
  PieChart,
  Flame,
  Scale,
  Vote,
  Wallet,
  Activity,
  ArrowDownUp,
  BarChart3,
  Boxes,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CircleHelp,
  Clock,
  Coins,
  Crosshair,
  Droplets,
  FileText,
  Link2,
  ListOrdered,
  Network,
  Send,
  ShoppingBasket,
  SlidersHorizontal,
  Tags,
  Timer,
  Waves,
  Waypoints,
}

export function getPaneIcon(name?: string): LucideIcon {
  if (!name) return LayoutGrid
  return PANE_ICONS[name] ?? LayoutGrid
}
