// Copyright (c) 2026 Juan Ignacio Molina Estrada
// SPDX-License-Identifier: FSL-1.1-Apache-2.0
// Durable design-sync prebuild for @pairlens/ui. Run before the converter
// (wired as cfg.buildCmd). Deterministic — safe to re-run on every sync.
//   1. Emit dist/*.d.ts (incl. dist/catalog.d.ts, the discovery/types entry).
//   2. Regenerate src/catalog.ts, .ds-tmp/bundle-entry.ts, and category docs.
//   3. Compile Tailwind v4 styles.css -> .ds-tmp/compiled.css (cssEntry),
//      stripping @font-face (the 3 @fontsource families ship via cfg.extraFonts).
import { writeFileSync, mkdirSync, readdirSync, readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..')
const PKG = join(REPO, 'packages/ui')
const run = (cmd, args, cwd) =>
  execFileSync(cmd, args, { cwd, stdio: 'inherit' })
const pascal = (s) =>
  s.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase())

const PRIMARY = {
  bell: 'BellIcon',
  blocks: 'BlocksIcon',
  'chart-line': 'ChartLineIcon',
  chart: 'ChartContainer',
  direction: 'DirectionProvider',
  'hand-coins': 'HandCoinsIcon',
  home: 'HomeIcon',
  'input-otp': 'InputOTP',
  layers: 'LayersIcon',
  resizable: 'ResizablePanelGroup',
  sonner: 'Toaster',
  waypoints: 'WaypointsIcon',
  workflow: 'WorkflowIcon',
}
const GROUPS = {
  Buttons: ['button', 'button-group', 'toggle', 'toggle-group', 'kbd'],
  Forms: [
    'input',
    'textarea',
    'native-select',
    'select',
    'combobox',
    'checkbox',
    'radio-group',
    'switch',
    'slider',
    'label',
    'field',
    'input-group',
    'input-otp',
    'calendar',
  ],
  'Data Display': [
    'table',
    'card',
    'avatar',
    'badge',
    'item',
    'empty',
    'chart',
    'chart-line',
    'aspect-ratio',
    'separator',
    'skeleton',
  ],
  Feedback: [
    'alert',
    'progress',
    'spinner',
    'sonner',
    'shimmering-text',
    'ai-orb',
  ],
  Overlays: [
    'dialog',
    'alert-dialog',
    'sheet',
    'drawer',
    'popover',
    'tooltip',
    'hover-card',
    'dropdown-menu',
    'context-menu',
    'menubar',
    'command',
  ],
  Navigation: [
    'tabs',
    'breadcrumb',
    'pagination',
    'navigation-menu',
    'sidebar',
    'accordion',
    'collapsible',
  ],
  Layout: ['scroll-area', 'resizable', 'carousel', 'blocks', 'workflow'],
  Icons: ['bell', 'hand-coins', 'home', 'layers', 'waypoints'],
  Utilities: ['direction'],
}
const primaryOf = (f) => PRIMARY[f] ?? pascal(f)

console.error('[prebuild] 1/3 tsc declarations')
run('bun', ['run', 'build'], PKG)

console.error('[prebuild] 2/3 regenerate catalog / bundle-entry / docs')
const files = readdirSync(join(PKG, 'src/components/ui'))
  .filter((f) => f.endsWith('.tsx'))
  .map((f) => f.replace('.tsx', ''))
  .sort()
const fileToGroup = {}
for (const [g, fs] of Object.entries(GROUPS))
  for (const f of fs) fileToGroup[f] = g
const ungrouped = files.filter((f) => !fileToGroup[f])
if (ungrouped.length) {
  console.error('[prebuild] UNGROUPED files:', ungrouped)
  process.exit(1)
}

writeFileSync(
  join(PKG, 'src/catalog.ts'),
  '// AUTO-GENERATED by .design-sync/prebuild.mjs — do not edit by hand.\n' +
    '// Flat catalog: one primary export per component. design-sync discovery/types entry.\n\n' +
    files
      .map((f) => `export { ${primaryOf(f)} } from './components/ui/${f}'`)
      .join('\n') +
    '\n',
)

mkdirSync(join(PKG, '.ds-tmp'), { recursive: true })
writeFileSync(
  join(PKG, '.ds-tmp/bundle-entry.ts'),
  '// AUTO-GENERATED by .design-sync/prebuild.mjs — full re-export surface for the DS bundle.\n' +
    "export { cn } from '../src/lib/utils'\nexport { useIsMobile } from '../src/hooks/use-mobile'\n" +
    // Expose sonner's `toast` on the bundle so previews importing { toast } from
    // '@pairlens/ui' share the SAME sonner ToastState store as the bundled <Toaster>
    // (otherwise a preview's own sonner copy publishes to a different store).
    "export { toast } from 'sonner'\n\n" +
    files.map((f) => `export * from '../src/components/ui/${f}'`).join('\n') +
    '\n',
)

const docsDir = join(REPO, '.design-sync/docs')
mkdirSync(docsDir, { recursive: true })
for (const f of files)
  writeFileSync(
    join(docsDir, `${primaryOf(f)}.md`),
    `---\ncategory: ${fileToGroup[f]}\n---\n`,
  )

console.error('[prebuild] 3/3 compile Tailwind css (strip @font-face)')
run(
  'bunx',
  [
    '@tailwindcss/cli',
    '-i',
    'src/styles.css',
    '-o',
    '.ds-tmp/compiled.raw.css',
    '--optimize',
  ],
  PKG,
)
let css = readFileSync(join(PKG, '.ds-tmp/compiled.raw.css'), 'utf8')
// Strip @font-face blocks — fonts ship via cfg.extraFonts (fontsource packages)
// so we don't carry broken ./files/*.woff2 url()s into the bundle css.
css = css.replace(/@font-face\s*\{[^}]*\}/g, '')
writeFileSync(join(PKG, '.ds-tmp/compiled.css'), css)
console.error(
  `[prebuild] done — compiled.css ${(css.length / 1024) | 0}KB, ${files.length} components`,
)
