// Copyright (c) 2026 Juan Ignacio Molina Estrada
// SPDX-License-Identifier: FSL-1.1-Apache-2.0
import { useMemo } from 'react'

import { parseResearchSections } from './parse-research-sections'
import { CatalystsSection } from './sections/catalysts-section'
import { DefaultSection } from './sections/default-section'
import { ExecutiveSummarySection } from './sections/executive-summary-section'
import { PriceActionSection } from './sections/price-action-section'
import { RiskFactorsSection } from './sections/risk-factors-section'
import { TradeSetupSection } from './sections/trade-setup-section'
import type { ResearchSection } from './parse-research-sections'

type SourceInfo = { url: string; title: string }

type SectionComponent = React.ComponentType<{
  section: ResearchSection
  sources: Array<SourceInfo>
  market?: string
  pair?: string
}>

const SECTION_RENDERERS: Record<string, SectionComponent> = {
  'executive-summary': ExecutiveSummarySection,
  'price-action-structure': PriceActionSection,
  'price-action': PriceActionSection,
  'catalysts-developments': CatalystsSection,
  'catalysts-recent-developments': CatalystsSection,
  'trade-setup': TradeSetupSection,
  'risk-factors': RiskFactorsSection,
}

/** Sections generated by the AI that we suppress (rendered separately) */
const HIDDEN_SLUGS = new Set(['sources', 'sources-references', 'references'])

export function ResearchSectionRenderer({
  report,
  sources,
  market,
  pair,
}: {
  report: string
  sources: Array<SourceInfo>
  market?: string
  pair?: string
}) {
  const sections = useMemo(
    () =>
      parseResearchSections(report).filter((s) => !HIDDEN_SLUGS.has(s.slug)),
    [report],
  )

  return (
    <div className="divide-y divide-border/30 text-sm leading-relaxed text-foreground">
      {sections.map((section, i) => {
        const Renderer = SECTION_RENDERERS[section.slug] ?? DefaultSection
        return (
          // Keyed by index, not slug: while a heading streams in character by
          // character its slug changes on every keystroke ("price" →
          // "price-action" → "price-action-structure"), and slug-keying would
          // unmount/remount the whole section each time — flashing sparklines
          // and jumping the scroll. Sections only append top-to-bottom while
          // streaming, so the positional index is stable.
          <div key={i} className="py-5 first:pt-0 last:pb-0">
            <Renderer
              section={section}
              sources={sources}
              market={market}
              pair={pair}
            />
          </div>
        )
      })}
    </div>
  )
}
