// Copyright (c) 2026 Juan Ignacio Molina Estrada
// SPDX-License-Identifier: FSL-1.1-Apache-2.0
import { validateManifest } from '@pairlens/shared/plugin-manifest-schema'
import { packPlugin } from '@pairlens/shared/plugin-package'

import type {
  CustomIndicatorDescriptor,
  CustomIndicatorMeta,
  CustomIndicatorModule,
  PluginManifest,
} from '@pairlens/shared/plugin-types'

// ---------------------------------------------------------------------------
// "Export as plugin" — turns one editor script into a standalone, sandbox-safe
// `chart:indicator` plugin zip (manifest.json + module.js). The generated
// module embeds the descriptor (meta + Python source) as JSON and has zero
// imports, so it loads unchanged in the plugin worker sandbox. Users install
// the zip via Plugins → Import.
// ---------------------------------------------------------------------------

const PLUGIN_ID_RE = /^[a-z0-9][a-z0-9-]{1,63}$/

/** Derive a manifest-valid plugin id from a free-form script name. */
export function slugifyPluginId(name: string): string {
  const slug = name
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '') // strip diacritics
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-')
    .slice(0, 64)
  // Ids must start alphanumeric and be at least 2 chars.
  const trimmed = slug.replace(/^-+/, '')
  if (PLUGIN_ID_RE.test(trimmed)) return trimmed
  return trimmed.length > 0
    ? `${trimmed}-indicator`.slice(0, 64)
    : 'my-indicator'
}

export function isValidPluginId(id: string): boolean {
  return PLUGIN_ID_RE.test(id)
}

export type IndicatorPluginExportInput = {
  /** Plugin id (slug) — validated against the manifest id rules. */
  id: string
  /** Human-readable plugin name (manifest.name). */
  name: string
  author?: string
  description?: string
  /** Last successfully extracted metadata of the script. */
  meta: CustomIndicatorMeta
  /** Entry Python source (defines meta + compute(ctx)). */
  source: string
  /** Helper modules the entry imports; packaged alongside it. */
  modules?: Array<CustomIndicatorModule>
}

export type IndicatorPluginExportResult =
  | {
      ok: true
      manifest: PluginManifest
      moduleText: string
      bytes: Uint8Array
      fileName: string
    }
  | { ok: false; errors: Array<string> }

/**
 * Build the plugin module source. Self-contained ESM with no imports —
 * descriptors are embedded as JSON so the sandbox can evaluate it directly.
 */
export function buildIndicatorPluginModule(
  manifest: PluginManifest,
  descriptors: Array<CustomIndicatorDescriptor>,
): string {
  return `// Generated by Pairlens — Python chart indicator plugin.
// Install via Plugins → Import. Runs in the terminal's local Python runtime.
export const manifest = ${JSON.stringify(manifest, null, 2)}

const descriptors = ${JSON.stringify(descriptors, null, 2)}

export function createPlugin(pluginManifest) {
  return {
    manifest: pluginManifest,
    status: 'installed',
    config: {},
    execute: async ({ capability }) => {
      if (capability !== 'chart:indicator') {
        throw new Error(
          "unsupported capability '" + capability + "'",
        )
      }
      return descriptors
    },
  }
}
`
}

/**
 * Build a downloadable plugin package (zip bytes) from an editor script.
 * Validates the generated manifest before packing; returns human-readable
 * errors instead of throwing so the dialog can surface them inline.
 */
export function buildIndicatorPluginPackage(
  input: IndicatorPluginExportInput,
): IndicatorPluginExportResult {
  const metaId = isValidPluginId(input.meta.id)
    ? input.meta.id
    : slugifyPluginId(input.meta.title || input.name)

  const descriptor: CustomIndicatorDescriptor = {
    meta: { ...input.meta, id: metaId, title: input.meta.title || input.name },
    language: 'python',
    source: input.source,
    ...(input.modules?.length ? { modules: input.modules } : {}),
  }

  const manifest = {
    id: input.id,
    name: input.name,
    version: '1.0.0',
    author: input.author?.trim() || 'Pairlens user',
    description:
      input.description?.trim() ||
      `Custom Python chart indicator: ${descriptor.meta.title}`,
    icon: 'SquareFunction',
    capabilities: [
      {
        id: 'chart:indicator' as const,
        singleton: false,
        markets: ['*'],
        priority: 50,
        streaming: false,
      },
    ],
    config: {},
    network: { hosts: [] as Array<string> },
  }

  const result = validateManifest(manifest)
  if (!result.valid) {
    return { ok: false, errors: result.errors }
  }

  const moduleText = buildIndicatorPluginModule(result.manifest, [descriptor])
  const bytes = packPlugin({ manifest: result.manifest, moduleText })
  return {
    ok: true,
    manifest: result.manifest,
    moduleText,
    bytes,
    fileName: `${result.manifest.id}.zip`,
  }
}
